# Setup
title:               nCovMemory
tagline:             'An Analysis'
description:         'Computer generated analysis of the nCvoMemory project, a database of articles related to the coronavirus epidemy in China'
url:                 https://alqua.github.io/website-nCovMemory-analysis
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alqua
  url:               https://github.com/Alqua

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
